name: Check if we can build the code
on:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependecies
        run: pnpm install
      - name: Build project
        run: pnpm run build
